const ASSET_STATUS = Object.freeze({
  OPERATIONAL: 'Operational',
  ISSUE_REPORTED: 'Issue Reported',
  UNDER_INSPECTION: 'Under Inspection',
  UNDER_MAINTENANCE: 'Under Maintenance',
  OUT_OF_SERVICE: 'Out of Service',
  RETIRED: 'Retired',
});

const ALL_ASSET_STATUSES = Object.values(ASSET_STATUS);

// Which asset statuses a given asset may move to. Retired is a terminal state
// reachable from anywhere (an admin can retire an asset regardless of state).
const ASSET_STATUS_TRANSITIONS = Object.freeze({
  [ASSET_STATUS.OPERATIONAL]: [
    ASSET_STATUS.ISSUE_REPORTED,
    ASSET_STATUS.OUT_OF_SERVICE,
    ASSET_STATUS.RETIRED,
  ],
  [ASSET_STATUS.ISSUE_REPORTED]: [
    ASSET_STATUS.UNDER_INSPECTION,
    ASSET_STATUS.OUT_OF_SERVICE,
    ASSET_STATUS.RETIRED,
  ],
  [ASSET_STATUS.UNDER_INSPECTION]: [
    ASSET_STATUS.UNDER_MAINTENANCE,
    ASSET_STATUS.OUT_OF_SERVICE,
    ASSET_STATUS.OPERATIONAL,
    ASSET_STATUS.RETIRED,
  ],
  [ASSET_STATUS.UNDER_MAINTENANCE]: [
    ASSET_STATUS.OPERATIONAL,
    ASSET_STATUS.OUT_OF_SERVICE,
    ASSET_STATUS.RETIRED,
  ],
  [ASSET_STATUS.OUT_OF_SERVICE]: [
    ASSET_STATUS.UNDER_MAINTENANCE,
    ASSET_STATUS.OPERATIONAL,
    ASSET_STATUS.RETIRED,
  ],
  [ASSET_STATUS.RETIRED]: [],
});

module.exports = { ASSET_STATUS, ALL_ASSET_STATUSES, ASSET_STATUS_TRANSITIONS };
