const HISTORY_ACTION = Object.freeze({
  ASSET_CREATED: 'ASSET_CREATED',
  ASSET_UPDATED: 'ASSET_UPDATED',
  ASSET_RETIRED: 'ASSET_RETIRED',
  ISSUE_REPORTED: 'ISSUE_REPORTED',
  ISSUE_AI_TRIAGED: 'ISSUE_AI_TRIAGED',
  ISSUE_ASSIGNED: 'ISSUE_ASSIGNED',
  ISSUE_STATUS_CHANGED: 'ISSUE_STATUS_CHANGED',
  MAINTENANCE_RECORDED: 'MAINTENANCE_RECORDED',
  ISSUE_RESOLVED: 'ISSUE_RESOLVED',
  ISSUE_CLOSED: 'ISSUE_CLOSED',
  ISSUE_REOPENED: 'ISSUE_REOPENED',
});

module.exports = { HISTORY_ACTION };
